server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

zuul:
  routes:
    account:
      path: /account/**
      url: http://localhost:8081/account
    auth:
      path: /auth/**
      url: http://localhost:8082/auth
    auth:
      path: /notification/**
      url: http://localhost:8083/notification
    auth:
      path: /registration/**
      url: http://localhost:8084/registration